### ISSUE TITLE
OPEN.MAC won't compile, 23 Fatal error(s)

### ISSUE THREAD

**Issue by ackshooerry** [LeoBinkowski/NABU#2]
OPEN.MAC, line 8, says "INCLUDE NLINKTAB.EXA" but the file name here is called "LINKTAB.EXA". Changing the file name to NLINKTAB.EXA on the NABU seems to fix the issue as it now compiles with no fatal errors. Might make sense to change the file name here.

**Comment by LeoBinkowski** [comment]
Thanks! I NLINKTAB.EXA and LINKTAB.EXA are actually the same, thus I culled it from the repo. I changed OPEN.MAC to reference LINKTAB.EXA instead.

**Comment by LeoBinkowski** [comment]
closed due to update to OPEN.MAC
